examples/simple.js, package.json, src/IframeUploader.jsx
=> bugfix: enhanced compatibility for ie

src/AjaxUploader.jsx
Sorry guys for introducing this bug in to your code, I was a bit to fast writing it. 
Hope you can forgive me! 
:cake: from me!
=> Fixed bug calling wrong method name

package.json, src/AjaxUploader.jsx, src/request.js, tests/index.spec.js, tests/starter.js
去掉superagent，ajax Upload直接使用xhr
close #20
=> feat: remove superagent

README.md, examples/simple.js, src/AjaxUploader.jsx, src/Upload.jsx, src/request.js
close #22 & ant-design/ant-design#677
=> support XHR headers

src/AjaxUploader.jsx, tests/request.spec.js
close #37 
解决方案：每次上传完成后，重新刷新 input 整个 dom 结构
=> fix(ajaxuploader): support ie10 upload the same file twice

src/AjaxUploader.jsx
close ant-design/ant-design#1989
=> Should reset input after beforeUpload reject

README.md
The first arg is response body rather than request
=> Update onSuccess docs in README

.travis.yml, examples/beforeUpload.js, src/AjaxUploader.jsx, src/Upload.jsx, src/request.js
@see https://github.com/react-component/upload/issues/33#issuecomment-284644039
=> feat: disable upload progress listener in request if onPress is not set

.gitignore, package.json, tests/request.spec.js, tests/uploader.spec.js
see react-component/react-component.github.io#12
=> feat: add es

src/IframeUploader.jsx, src/Upload.jsx
=> fix issue #80 & #81

src/AjaxUploader.jsx, src/request.js
Fix issue #84 .
Return xhr to get header information.
=> Fix issue #84.

.gitignore, examples/customRequest.html, examples/customRequest.js, package.json
- update .gitignore : should ignore package-lock.json file
- add example:  set  customRequest with xhr code based on axios;
=> add example for customRequest

src/Upload.jsx
在 https://github.com/react-component/upload/commit/08c801d988d6472a61c57e262bd8561edf2ce599 中，合并master出现了错误的操作
=> fix ref error

HISTORY.md, README.md, src/AjaxUploader.jsx
So this is the pull request with the requested changes. @afc163 I am sorry but I am not so familiar with github and somehow closed the other pull request.
=> fix: Changed openFileDialogOnClick to also prevent Enter key.

src/traverseFileTree.js
close ant-design/ant-design#16426
不太好写用例。
=> fix: webkitRelativePath is missing in Upload.Dragger

src/AjaxUploader.jsx, tests/uploader.spec.js
fix https://github.com/ant-design/ant-design/issues/17397
=> fix: multiple should work with drag

src/AjaxUploader.jsx
@zombieJ 
data 调用应该在 `transformFile` 之后
=> fix: data apply order should be after transformFile

src/AjaxUploader.jsx
修复bug: [#19372]https://github.com/ant-design/ant-design/issues/19372
close https://github.com/ant-design/ant-design/issues/19372
=> catch transformFile error

src/AjaxUploader.jsx
https://github.com/ant-design/ant-design/issues/19288
=> fix: selection box alert twice when use button

src/request.js
https://github.com/react-component/upload/issues/239
=> 为formdata.append增加第三个参数控制文件名称

README.md, src/Upload.jsx
relates https://github.com/react-component/upload/pull/215#issuecomment-622957633
=> remove unused onReady prop and update README.md

README.md, src/AjaxUploader.jsx, tests/uploader.spec.js
[#22529](https://github.com/ant-design/ant-design/issues/22529)
=> feat: data function support return promise(#22529)

src/AjaxUploader.jsx, tests/uploader.spec.js
fix https://github.com/ant-design/ant-design/issues/24653
=> fix: transformFile should be called before data function

src/AjaxUploader.jsx
在给 antd 写 test 的时候发现一处时序问题，request 如果是同步操作，会使得 `onProgress` `onSuccess` `onError` 在 `onStart` 之前触发。
=> fix: Upload order issue

src/AjaxUploader.tsx
FC 里时序需要梳理一下，timeout 和 useEffect 冲突导致多个 file 同时上传的时候不是一个稳定状态。这个改完 antd 里还要接着改。
ref https://github.com/ant-design/ant-design/issues/26536
=> refatcor: change timeout to promise

src/AjaxUploader.tsx, tests/uploader.spec.js
fix [#29563](https://github.com/ant-design/ant-design/issues/29563)
=> fix: beforeUpload调用后获取action & data值(#29563)

src/AjaxUploader.tsx, tests/uploader.spec.js
fix https://github.com/ant-design/ant-design/issues/29619
onChange 的时候，files 经过 accept 过滤。
=> fix: should filter files by accept when select dir

docs/examples/simple.tsx, package.json, src/AjaxUploader.tsx
Fix [Issue 29608 - Capture attribute for Upload Component](https://github.com/ant-design/ant-design/issues/29608)
=> [Upload]: support capture attribute

src/AjaxUploader.tsx, tests/uploader.spec.js
ref https://github.com/ant-design/ant-design/issues/29706
发个 alpha 版本，我测测。
=> fix: event return parsed file

src/attr-accept.ts, tests/uploader.spec.js
fix https://github.com/ant-design/ant-design/issues/29852
=> fix(accept): support * and */* value

src/interface.tsx
i think xhr should be optional
=> chore:change customRequest onSuccess prop optional

src/AjaxUploader.tsx
resolve https://github.com/ant-design/ant-design/issues/46562
=> fix: button trigger upload twice
