src/IframeUploader.jsx
src/Upload.jsx

1. 修复 ie8/9 拿不到 file.name 的问题。
2. 修复 ie8/9 下 input[type=file] 高度不对的问题。
3. 修复 safari 下进入了 iframe 模式的问题。（safari 下 typeof FormData 为 object）

Fix upload in ie and safari

---

src/AjaxUploader.jsx

The role-attribute is important when we make "none-interactive"
elements interactive, such as SPANs. This makes it easier for
person using screen readers and such to use the site.
(http://www.w3.org/TR/wai-aria/roles)
By having a tabIndex and support "enter" we can easily navigate
to the upload element, and enter it via the keyboard. This makes
our site more usable.

Added aria role and keyboard navigation.

---

package.json
src/request.js

Fix the problem that the uploading would fail if the server requires login by setting xhr with credentials,
[#26](https://github.com/react-component/upload/issues/26).

xhr with credentials

---

README.md
src/AjaxUploader.jsx
src/Upload.jsx
src/request.js

feat: change xhr.withCredentials as prop config, default false

---

README.md
src/AjaxUploader.jsx
src/IframeUploader.jsx
src/Upload.jsx

像阿里云的 OSS 需要把文件名放在 data 里，我们会把上传的文件名换成成 UUID，所以我希望能在 data 里拿到上传的文件对象，然后根据上传文件的后缀生成新的文件名。
顺便改正了 data 的 prop 验证。

把 file 传给 data 方法

---

package.json
src/request.js
tests/index.spec.js
tests/request.spec.js

1. allow all 2xx status as success status, not only 200
2. can close X-Requested-With header when set value as null
closes #33 #34 
cc @yiminghe @afc163

feat(request): fix issue #33 and #34

---

src/AjaxUploader.jsx

之前的代码拖拽时还是可以上传多个文件，并触发 before 事件

修复单选时可以拖拽多个文件的问题

---

src/AjaxUploader.jsx

Close: https://github.com/ant-design/ant-design/issues/2022

Use file object passed by Promise's `resolve` after beforeUpload

---

package.json
src/AjaxUploader.jsx
src/IframeUploader.jsx

ref: https://github.com/ant-design/ant-design/issues/3072

fix: should support className

---

src/AjaxUploader.jsx

add blob type

---

README.md
src/AjaxUploader.jsx
src/Upload.jsx

I found myself needing to change portions of the AjaxUploader component to get it working with AWS S3. Allowing for the component to have a custom request prop would make extensibility easier.

add custom request option

---

examples/beforeUpload.js
src/AjaxUploader.jsx

Close: https://github.com/ant-design/ant-design/issues/4015
如下可以限制最多上传三个文件：
```jsx
function beforeUpload(file, fileList) {
const shouldBeUpload = this.state.fileList.concat(fileList)
.slice(0, 3).indexOf(file) > -1;
// TODO
}
```

feat: expose `fileList` to beforeUpload

---

src/IframeUploader.jsx

For instance:
```html
<script>
... domainScript = '<script>document.domain="' + domain + '"</script>'
</script>
```
The close tag `</script>` in template string will break javaScript engine, so we need to use a variable to split it.

bugfix: split script close tag for html file inline usage

---

src/AjaxUploader.jsx

The component is currently a bit fragile: If a customRequest does not call `onSuccess()` / `onError()` upon completion or error, the `this.reqs[uid]` value will not be deleted, but === undefined, and then when the Upload component un-mounts, it will try to `abort()` an undefined request, and crash.

Fix crash if customRequest does not call onSuccess() / onError()

---

examples/beforeUpload.js
examples/simple.js
package.json
server.js
src/AjaxUploader.jsx
src/IframeUploader.jsx
src/Upload.jsx
src/index.js

Fix prop-types and create-react-class warning

---

package.json
src/AjaxUploader.jsx
src/attr-accept.js
tests/uploader.spec.js

Inline the  attr-accept to avoid import dist files compiled by babel5.
close ant-design/ant-design#8210
close https://github.com/ant-design/ant-design/issues/7515

make attr-accept inline

---

examples/simple.js
src/AjaxUploader.jsx
tests/uploader.spec.js

User can pass `id` to internal `input` element.
ref: https://github.com/ant-design/ant-design/issues/13036

support id prop

---

src/traverseFileTree.js
tests/uploader.spec.js

fix https://github.com/ant-design/ant-design/issues/14845

Fix missing rest files of directory upload

---

src/IframeUploader.jsx

fix file.name in ie9

---

src/AjaxUploader.jsx

Code in antd [here](https://github.com/ant-design/ant-design/blob/master/components/upload/Upload.tsx#L219) assumes that every file in `fileList: RcFile[]` has `uid` property.
When passes prop `beforeUpload` function to antd's `Upload` component and the  `beforeUpload` function returns false, react will throw a unique key error due to the lack of `uid`(antd's `UploadList` component [use `uid` as unique key](https://github.com/ant-design/ant-design/blob/master/components/upload/UploadList.tsx#L198)).

Fix: preprocess filelist, add uid before calling upload

---

.gitignore
README.md
examples/transformFile.html
examples/transformFile.js
src/AjaxUploader.jsx
src/request.js
tests/uploader.spec.js

你好! 我想增加一个 `transformFile` 的接口, 由于 `antd` `Uploader` 组件使用是此 `repo` 所以在这里发起一个 `pr`
普通的图片上传需求 由于业务需要 在 上传的时候 需要在原图片上增加水印 (前端canvas 增加) , 可以使用 `customRequest` 实现类似的需求, 就像 你们给的 [这个例子](https://github.com/react-component/upload/blob/master/examples/customRequest.js)
```js
const formData = new FormData();
if (data) {
Object.keys(data).map(key => {
formData.append(key, data[key]);
});
}
// 但是其实我只需要替换掉这里的 file
formData.append(filename, file);
axios
.post(action, formData, {
withCredentials,
headers,
onUploadProgress: ({ total, loaded }) => {
onProgress({ percent: Math.round(loaded / total * 100).toFixed(2) }, file);
},
})
.then(({ data: response }) => {
onSuccess(response, file);
})
.catch(onError);
```
其实我只需要 在 你们的 `request.js`  替换到这里的 `file` 变量 , 不需要单独实现请求, 和手动调用 类似 `onSuccess` `onError` 的回调 …

feat(ajaxUploader): add transformFile option for transform file before request

---

README.md
src/AjaxUploader.jsx
src/request.js
tests/request.spec.js

aws s3 need put method to upload file

add request method option

---

package.json
src/AjaxUploader.jsx
tests/uploader.spec.js

Resolves ant-design/ant-design#19084. Credit to @DylanVann for the dataOrAriaAttributeProps function found in react-component/notification#54

fix: Pass through data and aria attributes

---

.editorconfig
.eslintrc.js
.gitignore
.umirc.ts
LICENSE
README.md
docs/changelog.md
docs/demo/asyncAction.md
docs/demo/beforeUpload.md
docs/demo/customRequest.md
docs/demo/directoryUpload.md
docs/demo/drag.md
docs/demo/simple.md
docs/demo/transformFile.md
docs/examples/asyncAction.tsx
docs/examples/beforeUpload.tsx
docs/examples/customRequest.tsx
docs/examples/directoryUpload.tsx
docs/examples/drag.tsx
docs/examples/simple.tsx
docs/examples/transformFile.tsx
now.json
package.json
script/update-content.js
tsconfig.json
typings.d.ts

upload 的 demo 展示主要是看 console 的输出，目前 dumi 对这个还不支持，只能通过 F12 看。
想等等 这个 https://github.com/umijs/dumi/issues/409

chore: use dumi

---

src/attr-accept.ts
tests/uploader.spec.js

发个 minor 版本
ref https://github.com/ant-design/ant-design/issues/30403

chore: Pass invalidate type

---

src/AjaxUploader.tsx
tests/uploader.spec.js

fix https://github.com/ant-design/ant-design/issues/30403
**改动点:**
触发 `onChange` 的时候，只有选择目录的时候，使用 `accept` 过滤文件，否则直接放行。

chore: accept should skip when select files rather than dir

---

src/interface.tsx

Let ProgressEvent optional

---

src/AjaxUploader.tsx

fix https://github.com/react-component/upload/issues/488
并且能防止用户通过 js 打开上传文件框

fix: pass disabled prop to input

---

src/traverseFileTree.ts
tests/uploader.spec.js

Per the [DataTransferItem API](https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem/webkitGetAsEntry), if `webkitGetAsEntry()` is called on something that isn't a file or folder, null is returned. Sometimes when dragging and dropping a file, extra string meta data seems to be associated with the event (examples, dragging and dropping an image blob from a different browser tab, or dragging a message from the Outlook desktop app).
This causes an exception to be thrown, because the `_traverseFileTree` function assumes each item to be a valid `InternalDataTransferItem`. The end result is any valid file in the items array will not get uploaded after this exception occurs. If we can instead gracefully handle this case, valid directories will still get crawled and valid files will …

fix: gracefully handle null items

---

src/AjaxUploader.tsx
src/Upload.tsx
src/interface.tsx
tests/uploader.spec.js

Based on this discussion https://github.com/ant-design/ant-design/issues/46215
added the property `hasControlInside` which manages `tabIndex` and `role` attributes on the wrapper of `Upload` component to prevent nesting of focusable elements and a11y issues in situation like this:
```tsx
<Upload>
<button>Upload</button>
</Upload>
```
To disable "button like" behavior and double focus when `Upload` contains controls inside now we can use it this way:
```tsx
<Upload hasControlInside>
<button>Upload</button>
</Upload>
```

hasControlInside prop to enable/disable button like behavior - tabIndex and role on the wrapper

---

src/AjaxUploader.tsx

Same thing as #524 but for `antd@4`

fix: Fix btn logic for antd4

---

docs/demo/dragDirectory.md
docs/examples/dragDirectory.tsx

目前upload组件demo中缺少拖拽上传文件夹示例，添加dragDirectory拖拽上传文件夹demo，方便查看拖拽上传文件夹交互及beforeUpload回调参数；

demo: 添加dragDirectory拖拽上传文件夹demo

---

src/traverseFileTree.ts
tests/uploader.spec.tsx

🔗 相关 Issue
https://github.com/ant-design/ant-design/issues/49252
https://github.com/react-component/upload/issues/453
ps:之前提过[pr](https://github.com/react-component/upload/pull/559)，但是commit记录太乱了,大佬后面也没看就重新开了一个
💡 需求背景和解决方案
当拖拽上传文件夹时，需要手动解析文件树，原代码在解析到子文件为非文件夹时直接执行后续而非等待全部文件解析完成，与普通上传的表现不一致。添加其他变量确保文件全部解析后再进行后续操作
主要改动的地方:
1.traverseFileTree.ts中添加restFile变量记录剩余文件数量，将原本的loopFiles函数移动到了traverseFileTree里便于访问restFile变量
2.原测试中工具函数makeFileSystemEntry逻辑错误，导致当上传的文件夹包含子文件夹时无法进入开始上传逻辑，在测试 https://github.com/react-component/upload/blob/master/tests/uploader.spec.tsx#L377 将webp后缀改成png后测试任然通过可以验证这个bug
3.添加了相关测试

fix:delay folder upload until all children files are parsed when drag

---

src/AjaxUploader.tsx
src/traverseFileTree.ts
tests/uploader.spec.tsx

fix https://github.com/ant-design/ant-design/issues/50080
https://github.com/react-component/upload/blob/80e5228ffd58114974b7eb98d6f93d8a6213bb7c/src/traverseFileTree.ts#L20-L31
出现这个bug的原因大概率是因为异步api导致，`dirReader.readEntries`是异步且被递归调用，`walkFiles`这个方法又是同步执行的，while循环结束了一会之后才会走入`readEntries`的回调，导致`callback`其实是提前拿了一个空数组就提前结束。

fix: upload drag directory can not work

---

src/AjaxUploader.tsx
src/Upload.tsx
tests/uploader.spec.tsx

1. This reverts commit d94d644f61457098a1c57542519337d20acc91d9.
2. add unit test

Revert "feat: support name prop (#574)"
